# -*- coding: utf-8 -*-

from . import res_partner
from . import fleet_route
from . import product_partner_tax
from . import product
from . import fleet_vehicle
from . import master_destination
from . import master_origin
from . import crm_lead
from . import sale_order
from . import fleet_do
from . import account_move
from . import create_contract
from . import fleet_geofence
from . import disciplinary_status
from . import disciplinary_action_plan
from . import emergency_contact
from . import hr_employee
from . import hr_violation
from . import tier_definition
from . import hr_insurance
from . import dayofweek
from . import fleet_vehicle_model_category
from . import product_customer
from . import delivery_category
from . import fleet_vehicle_status
from . import fleet_hpp
from . import vehicle_dashboard
from . import accounting_dashboard
from . import account_account
from . import account_move_line
from . import account_asset
from . import fleet_service_type
from . import fleet_vehicle_log_services
from . import fleet_bop
from . import fleet_last_checkpoint
from . import hr_resume_line
from . import m_fleet_route
from . import fleet_service_category
from . import fleet_vehicle_status_log
from . import fleet_last_checkpoint_sync_wizard
from . import res_company
from . import purchase_order
from . import account_tax
from . import account_payment
from . import fleet_do_report
from . import program_category
from . import invoice_monitoring
from . import fleet_vehicle_ewd
from . import fleet_vehicle_assignation_log
