# -*- coding: utf-8 -*-
{
    'name': "JST - Demo Kalla BJU Transporter",

    'summary': "Custom Module for Demo",

    'description': """
    """,

    'author': "Juke Solusi Teknologi",
    'website': "https://www.jukesolutions.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/17.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['hr_skills', 'base', 'crm', 'sale', 'sale_crm', 'fleet', 'product', 'stock_dropshipping', 'sale_planning', 'sale_stock', 'sale_expense', 'account_asset', 'base_tier_validation', 'jst_tp_company', 'purchase'],

    # always loaded
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/fleet_security.xml',
        'data/ir_sequence.xml',
        'data/server_action.xml',
        'wizard/driver_selection_wizard.xml',
        'views/fleet_route.xml',
        'views/product.xml',
        'views/fleet_vehicle.xml',
        # 'views/crm_lead.xml',
        'views/sale_order.xml',
        'views/res_partner.xml',
        'views/sale_order_line.xml',
        'views/fleet_do.xml',
        'views/create_contract.xml',
        'reports/report_config.xml',
        'reports/fleet_do.xml',
        'views/fleet_geofence.xml',
        'views/hr_employee.xml',
        'views/hr_violation.xml',
        'views/hr_insurance.xml',
        'reports/report_config.xml',
        'reports/bop_do.xml',
        'wizard/mcm_driver.xml',
        'views/dayofweek.xml',
        'views/fleet_vehicle_model_category.xml',
        'views/product_customer.xml',
        'views/delivery_category.xml',
        'views/master_origin.xml',
        'views/master_destination.xml',
        'reports/invoice_custom.xml',
        'views/fleet_vehicle_status.xml',
        'views/fleet_hpp.xml',
        'views/vehicle_dashboard_menu.xml',
        'views/customer_dashboard_menu.xml',
        # 'views/customer_dashboard_outstanding_menu.xml',
        'views/outstanding_customers_dashboard_menu.xml',
        'views/dashboard_menu.xml',
        'views/account_assets.xml',
        'views/fleet_vehicle_log_services.xml',
        'views/fleet_bop.xml',
        'views/fleet_last_checkpoint.xml',
        'views/hr_resume_line.xml',
        'views/fleet_route_masterdata.xml',
        'views/fleet_service_category.xml',
        'views/fleet_service_type.xml',
        'views/fleet_vehicle_cron.xml',
        'views/tier_definition_view.xml',
        'views/wizard_sync_checkpoint_view.xml',
        'views/purchase_order.xml',
        'views/res_company.xml',
        'views/account_move.xml',
        'views/account_tax.xml',
        'views/do_monitoring_menu.xml',
        'views/so_monitoring_menu.xml',
        'views/fleet_monitoring_menu.xml',
        'views/fleet_do_report_views.xml',
        'views/fleet_do_report_sync_wizard_views.xml',
        'views/program_category.xml',
        'views/move_dashboard_menu.xml',
        'views/product_partner_tax.xml',
        'views/disciplinary_status.xml',
        'views/disciplinary_action_plan.xml',
        'views/emergency_contact.xml',

        # data import
        'data/fleet_service_category_data.xml',
        'data/fleet_do_cron.xml',
        'data/emergency_contact_relationship.xml',

        # report
        'reports/account_move_report.xml',
        'reports/invoice_detail_order_report.xml',
    ],
    "installable": True,
    "application": True,
    'assets': {
        'web.assets_backend': [
            'jst_demo_kalla_bju_transporter/static/src/js/**/*',
            'jst_demo_kalla_bju_transporter/static/src/js/vehicle_dashboard.js',
            'jst_demo_kalla_bju_transporter/static/src/xml/vehicle_dashboard.xml',
            'jst_demo_kalla_bju_transporter/static/src/js/customer_dashboard.js',
            'jst_demo_kalla_bju_transporter/static/src/xml/customer_dashboard.xml',
            # 'jst_demo_kalla_bju_transporter/static/src/js/customer_dashboard_outstanding.js',
            # 'jst_demo_kalla_bju_transporter/static/src/xml/customer_dashboard_outstanding.xml',
            'jst_demo_kalla_bju_transporter/static/src/js/outstanding_customers_dashboard.js',
            'jst_demo_kalla_bju_transporter/static/src/xml/outstanding_customers_dashboard.xml',
            'jst_demo_kalla_bju_transporter/static/src/js/dashboard.js',
            'jst_demo_kalla_bju_transporter/static/src/xml/accounting_dashboard_template.xml',
            'jst_demo_kalla_bju_transporter/static/src/css/dashboard.css',
            'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js',
            'https://cdn.jsdelivr.net/npm/chart.js',
            'https://cdn.jsdelivr.net/npm/chart.js@4.4.8/dist/chart.umd.min.js',
            'jst_demo_kalla_bju_transporter/static/lib/chart.js/chart.umd.js',
            'https://cdn.jsdelivr.net/npm/recharts@2.1.9/umd/Recharts.min.js',
            'jst_demo_kalla_bju_transporter/static/src/xml/hr_resume_line_templates.xml',
            'jst_demo_kalla_bju_transporter/static/src/js/hide_add_line.js',
            'jst_demo_kalla_bju_transporter/static/src/xml/do_monitoring.xml',
            'jst_demo_kalla_bju_transporter/static/src/xml/so_monitoring.xml',
            'jst_demo_kalla_bju_transporter/static/src/js/do_monitoring.js',
            'jst_demo_kalla_bju_transporter/static/src/js/so_monitoring.js',
            'jst_demo_kalla_bju_transporter/static/src/xml/fleet_monitoring.xml',
            'jst_demo_kalla_bju_transporter/static/src/js/fleet_monitoring.js',
            'jst_demo_kalla_bju_transporter/static/src/xml/move_monitoring.xml',
            'jst_demo_kalla_bju_transporter/static/src/js/move_monitoring.js',
        ],
    }
}
